import { jsPDF } from "jspdf";

// Only the fields export actually needs — both SummaryResponse (owner
// view) and SharedSummary (public view) satisfy this structurally, so
// either can be passed in without a cast. videoUrl/videoId are YouTube-
// only now; audio/PDF uploads have neither, just a sourceFilename.
export interface ExportableSummary {
  title: string | null;
  sourceType: "youtube" | "audio" | "pdf";
  sourceFilename?: string | null;
  videoUrl?: string | null;
  videoId?: string | null;
  summary: string;
  bulletPoints: string[];
}

function safeFilename(summary: ExportableSummary): string {
  const fallback = summary.videoId || summary.sourceFilename || "summary";
  const base = (summary.title || fallback)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 60);
  return base.replace(/^-+|-+$/g, "") || "summary";
}

function sourceLine(summary: ExportableSummary): string {
  if (summary.sourceType === "youtube" && summary.videoUrl) return summary.videoUrl;
  if (summary.sourceType === "audio") return `Audio file: ${summary.sourceFilename || "upload"}`;
  return `PDF: ${summary.sourceFilename || "upload"}`;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportSummaryAsTxt(summary: ExportableSummary) {
  const lines = [
    summary.title || "Summary",
    sourceLine(summary),
    "",
    "SUMMARY",
    summary.summary,
    "",
    "KEY POINTS",
    ...summary.bulletPoints.map((point) => `- ${point}`),
    "",
    "Generated by Synthary",
  ];

  downloadBlob(
    new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" }),
    `${safeFilename(summary)}.txt`
  );
}

export function exportSummaryAsPdf(summary: ExportableSummary) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const marginX = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - marginX * 2;
  let y = 25;

  function ensureSpace(neededMm: number) {
    if (y + neededMm > pageHeight - 20) {
      doc.addPage();
      y = 25;
    }
  }

  function writeParagraph(text: string, { fontSize = 11, lineHeight = 6, gapAfter = 8 } = {}) {
    doc.setFontSize(fontSize);
    const wrapped: string[] = doc.splitTextToSize(text, usableWidth);
    for (const line of wrapped) {
      ensureSpace(lineHeight);
      doc.text(line, marginX, y);
      y += lineHeight;
    }
    y += gapAfter;
  }

  // Title
  doc.setFont("helvetica", "bold");
  writeParagraph(summary.title || "Summary", { fontSize: 18, lineHeight: 8, gapAfter: 2 });

  // Source line — a clickable link for YouTube, plain text otherwise
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  ensureSpace(6);
  if (summary.sourceType === "youtube" && summary.videoUrl) {
    doc.setTextColor(80, 80, 200);
    doc.textWithLink(summary.videoUrl, marginX, y, { url: summary.videoUrl });
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setTextColor(120, 120, 120);
    doc.text(sourceLine(summary), marginX, y);
    doc.setTextColor(0, 0, 0);
  }
  y += 12;

  // Summary section
  doc.setFont("helvetica", "bold");
  writeParagraph("Summary", { fontSize: 13, lineHeight: 7, gapAfter: 2 });
  doc.setFont("helvetica", "normal");
  writeParagraph(summary.summary, { fontSize: 11, lineHeight: 6, gapAfter: 8 });

  // Key points section
  doc.setFont("helvetica", "bold");
  writeParagraph("Key Points", { fontSize: 13, lineHeight: 7, gapAfter: 2 });
  doc.setFont("helvetica", "normal");
  for (const point of summary.bulletPoints) {
    writeParagraph(`•  ${point}`, { fontSize: 11, lineHeight: 6, gapAfter: 4 });
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  ensureSpace(10);
  doc.text("Generated by Synthary", marginX, pageHeight - 12);

  doc.save(`${safeFilename(summary)}.pdf`);
}
